name: Apache Guacamole RDP Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-guacamole:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

    - name: Run Guacamole Docker container
      run: |
        sudo docker pull guacamole/guacamole
        sudo docker pull guacamole/guacd

        # Run guacd (Guacamole daemon)
        sudo docker run --name guacd -d guacamole/guacd

        # Run Guacamole web application
        sudo docker run --name guacamole -d -e GUACD_HOSTNAME=guacd -e MYSQL_HOSTNAME=localhost -e MYSQL_PORT=3306 -e MYSQL_DATABASE=guacamole_db -e MYSQL_USER=guacamole_user -e MYSQL_PASSWORD=guacamole_password -p 8080:8080 guacamole/guacamole

    - name: Set up MySQL (for Guacamole)
      run: |
        sudo docker run --name guacamole-mysql -d -e MYSQL_ROOT_PASSWORD=root_password -e MYSQL_DATABASE=guacamole_db -e MYSQL_USER=guacamole_user -e MYSQL_PASSWORD=guacamole_password -p 3306:3306 mysql:5.7

    - name: Wait for Guacamole to be ready
      run: sleep 60  # Wait for services to initialize

    - name: Expose the RDP port via ngrok
      run: |
        # Download ngrok
        curl -s https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -o ngrok.zip
        unzip ngrok.zip
        chmod +x ngrok

        # Set up ngrok to tunnel the RDP port (3389)
        ./ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
        ./ngrok tcp 3389 &

    - name: Send Guacamole Server URL (RDP accessible)
      run: echo "Your Guacamole URL is"
